### ISSUE TITLE
Looks like it broken 

### ISSUE THREAD

**Issue by Shivaprasad2452** [anoopjangra/pynse#3]
INFO:pynse.pynse:downloading market status
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.nseindia.com:443
DEBUG:urllib3.connectionpool:https://www.nseindia.com:443 "GET /api/marketStatus HTTP/1.1" 401 272
Traceback (most recent call last):
  File "/Users/shivap/Documents/shivper/untitled/pynsenettext.py", line 14, in <module>
    nse.market_status()
  File "/Users/shivap/Documents/shivper/VittIdeas/untitled/lib/python3.7/site-packages/pynse/pynse.py", line 223, in market_status
    return self.__get_resp(url=url).json()
  File "/Users/shivap/Documents/shivper/VittIdeas/untitled/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by anoopjangra** [comment]
upgrade using
`pip install pynse==0.1.4`
